default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blind_date_development
  username: blind_date_user
  password: password
  host: db

test:
  <<: *default
  database: blind_date_test
  username: blind_date_user
  password: password
  host: db

production:
  <<: *default
  database: blind_date_production
  username: blind_date
  password: <%= ENV["BLIND_DATE_DATABASE_PASSWORD"] %>
